### ISSUE TITLE
A default bottom margin exists, even when bottomEdgeSpacing is set to 0.

### ISSUE THREAD

**Issue by hossam1244** [r1n1os/sliding_action_button#1]
**Issue description:** 

   There's a bottom margin between the icon and the container even when bottomEdgeSpacing is set to 0

![Simulator Screenshot - iPhone 15 Pro - 2024-07-21 at 15 47 24](https://github.com/user-attachments/assets/9ac60434-32d6-423e-8ab3-bf8ac0c86784)

My Code: 
`CircleSlideToActionButton(
          width: 250,
          parentBoxRadiusValue: 27,
          circleSlidingButtonSize: 50,
          bottomEdgeSpacing: 0,
          leftEdgeSpacing: 0,
          rightEdgeSpacing: 0,
          initialSlidingActionLabel: 'Add To Basket',
          finalSlidingActionLabel: 'Added To Basket',
          circleSlidingButtonIcon: const Icon(
            Icons.add_shopping_cart,
            color: Colors.orange,
          ),
          parentBoxBackgroundColor: Colors.orange,
          parentBoxDisableBackgroundColor: Colors.grey,
          /*
                  In case you want to use gradient colors instead of single color uncomment those lines.
                  Reminder that you have to remove the lines configuring single color
                  (parentBoxBackgroundColor, parentBoxDisableBackgroundColor)
                  parentBoxGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),
                  parentBoxDisableGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),*/
          circleSlidingButtonBackgroundColor: Colors.white,
          isEnable: true,
          onSlideActionCompleted: () {
            print("Sliding action completed");
          },
          onSlideActionCanceled: () {
            print("Sliding action cancelled");
          },
        )`

**Comment by r1n1os** [comment]
Hi @hossam1244 Thank you for the feedback.

Because I'm using Stack to build this UI by default the Stack is setting the childrens at start(Left) top thats why this is happening. However, I will handle it by default to be correct alighn

**Comment by r1n1os** [comment]
**This has been resolve in version 0.0.3**
