### ISSUE TITLE
The icon exceeds the container when leftEdgeSpacing is added.

### ISSUE THREAD

**Issue by hossam1244** [r1n1os/sliding_action_button#2]
![Simulator Screenshot - iPhone 15 Pro - 2024-07-21 at 15 51 42](https://github.com/user-attachments/assets/2eaa2e14-8e19-4242-b04d-aae2dd3ac5f2)

**My Code:** 

`CircleSlideToActionButton(
          width: 250,
          parentBoxRadiusValue: 27,
          circleSlidingButtonSize: 50,
          bottomEdgeSpacing: 0,
          leftEdgeSpacing: 20,
          rightEdgeSpacing: 0,
          initialSlidingActionLabel: 'Add To Basket',
          finalSlidingActionLabel: 'Added To Basket',
          circleSlidingButtonIcon: const Icon(
            Icons.add_shopping_cart,
            color: Colors.orange,
          ),
          parentBoxBackgroundColor: Colors.orange,
          parentBoxDisableBackgroundColor: Colors.grey,
          /*
                  In case you want to use gradient colors instead of single color uncomment those lines.
                  Reminder that you have to remove the lines configuring single color
                  (parentBoxBackgroundColor, parentBoxDisableBackgroundColor)
                  parentBoxGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),
                  parentBoxDisableGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),*/
          circleSlidingButtonBackgroundColor: Colors.white,
          isEnable: true,
          onSlideActionCompleted: () {
            print("Sliding action completed");
          },
          onSlideActionCanceled: () {
            print("Sliding action cancelled");
          },
        )`

**Comment by r1n1os** [comment]
Hi @hossam1244 Thank you for the feedback.

I will investigate and resolve this

**Comment by r1n1os** [comment]
**This has been resolve in version 0.0.3**
