### ISSUE TITLE
There is a UI issue with sliding when the button is set to full width.

### ISSUE THREAD

**Issue by hossam1244** [r1n1os/sliding_action_button#3]
https://github.com/user-attachments/assets/ed97b7d4-85b8-4bdc-b7b6-e896af8f2ca1

**My Code:** 

CircleSlideToActionButton(
          width: double.infinity,
          parentBoxRadiusValue: 27,
          circleSlidingButtonSize: 50,
          bottomEdgeSpacing: 0,
          leftEdgeSpacing: 0,
          rightEdgeSpacing: 0,
          initialSlidingActionLabel: 'Add To Basket',
          finalSlidingActionLabel: 'Added To Basket',
          circleSlidingButtonIcon: const Icon(
            Icons.add_shopping_cart,
            color: Colors.orange,
          ),
          parentBoxBackgroundColor: Colors.orange,
          parentBoxDisableBackgroundColor: Colors.grey,
          /*
                  In case you want to use gradient colors instead of single color uncomment those lines.
                  Reminder that you have to remove the lines configuring single color
                  (parentBoxBackgroundColor, parentBoxDisableBackgroundColor)
                  parentBoxGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),
                  parentBoxDisableGradientBackgroundColor:
                      LinearGradient(colors: [Colors.red, Colors.white]),*/
          circleSlidingButtonBackgroundColor: Colors.white,
          isEnable: true,
          onSlideActionCompleted: () {
            print("Sliding action completed");
          },
          onSlideActionCanceled: () {
            print("Sliding action cancelled");
          },
        )

**Comment by r1n1os** [comment]
Hi @hossam1244 Thank you for the feedback.

I will investigate and fix the issue

**Comment by r1n1os** [comment]
**This has been resolve in version 0.0.3**
